// Boost Software License - Version 1.0 - August 17th, 2003

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.


#ifndef SNAKE_HPP
#define SNAKE_HPP
#include "hwlib.hpp"
#include "../../lib/MPU.hpp"

using namespace hwlib;
class block {
protected:
    window & w;
public:
    xy start;
    xy end;
    xy bounce;
    block(window & w,xy  start, xy  end, xy bounce):
        w(w),
        start(start),
        end(end),
        bounce(bounce)
        {}
    virtual void draw() = 0;
    virtual void update() = 0;
    virtual void interact(const block & other) = 0;

};

class head :public block {
private:
    xy eye;
public:
    head(window & w,xy  start, xy  end, xy bounce, xy eye):
        block(w,start,end ,bounce),
        eye(eye)
        {}
    void  draw();
    void update();
    l void interact(const block & other) ;
};
#endif
